Fix/pdirefresh
hub-usp-inovacao/platform pull request #174
Opened 2023-05-19 15:08 UTC by luizcarlosdk

2023-05-19 15:11 UTC, luizcarlosdk commented
There is 2 things to change, the "keywords = row[13]?.split(";")?.toSet()" is giving out-of-bound due the fact that the PDI List length is 12, but we do have this information on auspin drive.

fixed the first issue, we need to show this keywords in frontend.

2023-05-19 15:12 UTC, luizcarlosdk commented
error print:

![image](https://github.com/hub-usp-inovacao/platform/assets/61715930/a94552af-478d-4afe-b879-5e71c7dad3dd)

2023-05-30 08:18 UTC, jooaodanieel requested changes
Ponto mais importante: testar de fato o comportamento de limpar o BD no RefreshPDI.

2023-05-30 08:18 UTC, jooaodanieel commented on frontend/modules/Catalog/pages/inovacao.vue
> +        <p class="body-2">{{ item.keywords.join(';') }}</p>
Vale a pena dar join por `"; "`(com espaço depois do ponto-e-vírgula) ao invés de `";"` (sem espaço)

2023-06-26 14:02 UTC, jooaodanieel approved these changes
The major issue is, actually, something small (which is good, means the PR is of quality): the same serialization code repeats 3 times in different places of the application. I left a food-for-thought in the first occurrence.
The other issue is related to the interval considered for deleting data (of 5 seconds).

Think about those things. If any other change is felt as necessary, do it. Otherwise, I'm leaving the PR review as approved, so you can merge it without any further changes.

2023-06-28 17:29 UTC, merged