add sensitive data field to company model
hub-usp-inovacao/platform pull request #183
Opened 2023-06-21 17:56 UTC by mariliatd

2023-07-23 21:00 UTC, mariliatd commented
Os dados de Colaboradores (Staff) e Faturamento (Revenue) já estão sendo mostrados corretamente no formulário de atualizações.
Em relação aos dados de Investimento (Investment), encontramos dificuldade em fazer o componente _switch_ de `received_investment` ser ligado automaticamente no formulário, quando este tem valor _true_, após adicionar este campo no modelo `company`.
Depois, acabamos tendo problemas em atualizar o banco de dados (`rake fetch`) com os campos adicionados no modelo `company`, impedindo novos testes.

2023-07-26 19:53 UTC, mariliatd commented
O componente _switch_ do valor `received` não liga automaticamente mesmo quando tem valor _true_. Porém, os dados de `investments` e `investmentsValues` ficam disponíveis quando `received` é verdadeiro.

2023-07-28 15:43 UTC, luizcarlosdk commented
> O componente _switch_ do valor `received` não liga automaticamente mesmo quando tem valor _true_. Porém, os dados de `investments` e `investmentsValues` ficam disponíveis quando `received` é verdadeiro.

Vocês podem trocar o componente ou readaptar ele. O valor ser true mas no front ser false podem gerar complicações

2023-07-28 15:44 UTC, luizcarlosdk commented
É necessário se atentar aos erros do linter

2023-08-08 17:55 UTC, josemayer commented
- A validação do campo `received` do _backend_ possui um problema:

  <img width="335" src="https://github.com/hub-usp-inovacao/platform/assets/75316256/a49007e5-af0d-452c-a417-d238a4817e03">
  
  Ela exige que, se a empresa tiver recebido algum investimento, todos os tipos de investimento sejam não-nulos (o que, em regra, não é válido, já que o _frontend_ permite a seleção somente dos tipos de investimentos que foram recebidos). Uma abordagem de correção, que considera que pelo menos um dos tipos de investimento sejam não-nulos, é essa:
  
  <img width="391" src="https://github.com/hub-usp-inovacao/platform/assets/75316256/5f396c3f-d018-428e-b767-905bd673b677">

- Algumas empresas na planilha possuem a formatação de investimentos recebidos como 'R${valor}' ou 'R$ {valor}'. A validação do _backend_ permite só o segundo caso como válido (pelo que vi na planilha, são poucos casos sem o espaço, nada preocupante). Há duas formas de solucionar isso:
  - Solicitar à AUSPIN que utilize uma formatação uniforme para todas as empresas
  - Permitir, no _backend_, as duas validações, alterando a seguinte função de validação, no arquivo `backend/app/models/investment.rb`:

    <img width="439" src="https://github.com/hub-usp-inovacao/platform/assets/75316256/7a81d714-dfae-47ab-956e-a01818c788b8">

- Os campos `pipe`, `venture`, `equity` e `others` não estão sendo enviados do _frontend_ para o _backend_. Se a empresa tiver selecionado algum deles e preenchido os valores recebidos, a instância de atualização de empresa fica com valor nulo, já que a atualização não é passada. Abaixo, há um exemplo do que é enviado ao completar o formulário (somente os campos `own` e `angel`, apesar de PIS-PASEP estar selecionado no _array_ `investments`:

  <img width="431" src="https://github.com/hub-usp-inovacao/platform/assets/75316256/ad28f0bc-d1c3-4f68-b977-cacbb1556046">

2023-08-08 17:57 UTC, josemayer requested changes
No comentário anterior, revisei alguns dos problemas do PR a serem corrigidos.

2023-08-11 20:01 UTC, josemayer requested changes
Pequena mudança solicitada no comentário acima.

2023-08-25 16:27 UTC, josemayer approved these changes

2023-10-19 18:29 UTC, merged