Update partner's NUSP to accept only numerical values
hub-usp-inovacao/platform pull request #194
Opened 2023-08-10 18:54 UTC by josemayer

2023-08-11 00:51 UTC, clarayuki approved these changes

2023-08-11 13:50 UTC, luizcarlosdk requested changes

2023-08-11 13:50 UTC, luizcarlosdk commented on backend/app/models/partner.rb
> +  def numeric_nusp?
caso de nusp não ser um numérico deve ser adicionado aos testes, o teste atual apenas verifica se o nusp não é vazio.

2023-10-19 18:25 UTC, luizcarlosdk approved these changes

2023-10-19 18:26 UTC, merged