Feat/skills update request
hub-usp-inovacao/platform pull request #7
Opened 2022-05-20 13:26 UTC by luizcarlosdk

2022-05-20 13:48 UTC, jooaodanieel requested changes

2022-05-20 13:48 UTC, jooaodanieel commented on frontend/pages/competencias/atualizar/solicitar.vue
> +      </v-row>
Aqui o ideal seria pedir o NUSP do professor. O email é uma inferência feita no back a partir do NUSP informado.

Só pedir o email assim é uma vulnerabilidade, porque alguém poderia inserir um email qualquer e teríamos que lembrar de validar esse email com os cadastrados.

2022-05-20 13:48 UTC, jooaodanieel commented on backend/app/controllers/skill_updates_request_controller.rb
> +        @skill = Skill.where({ email: email }).first
Mesma questão que comentei no front (aqui deveria ser o nusp)

2022-05-20 13:48 UTC, jooaodanieel commented on backend/app/mailers/application_mailer.rb
> +  def skill_update_token(skill_email, token)
Você criou só a view `.html.erb`, mas precisa criar uma versão texto puro `.text.erb` (alguns clientes de email não aceitam html como corpo do email)

Dá uma olhada no de Empresas, tem ambos para você se basear

2022-05-20 13:48 UTC, jooaodanieel commented on backend/app/models/skill_update_request.rb
> +  embeds_one :email
Por que cê usou o `embeds_one` aqui? Acho que o melhor é ter um `field` para o email

2022-07-03 02:20 UTC, jooaodanieel commented
Podemos matar sem dar merge?

2022-07-03 03:01 UTC, luizcarlosdk commented
> Podemos matar sem dar merge?

infelizmente

2022-07-03 03:02 UTC, closed without merging