Handle null url case
hub-usp-inovacao/platform pull request #79
Opened 2022-12-02 21:33 UTC by BrizaMel

Signed-off-by: BrizaMel <brizamel.dias@gmail.com>
Co-authored-by: Marília Dicezare <mariliatd@gmail.com>

2022-12-08 09:33 UTC, jooaodanieel requested changes
Além da pergunta, faltaram testes cobrindo essa mudança.

[no back, tanto em rails quanto no kotlin, temos uma cobertura legal de testes, não podemos perder]

2022-12-08 09:33 UTC, jooaodanieel commented on server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/CatalogInitiativeRepositoryImpl.kt
> +    }
Essa separação era necessária?

2022-12-09 22:25 UTC, mariliatd commented on server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/CatalogInitiativeRepositoryImpl.kt
> +    }
Só para confirmar, precisamos criar um teste para verificar se a url é null? Pelo que vimos, os testes cobertos são referentes aos parâmetros de busca apenas (e url não é um parâmetro de busca).
Sobre a separação, não era necessária, mas como todos os outros repositórios estavam dessa forma, fizemos a alteração para deixar padronizado.

2022-12-13 12:29 UTC, jooaodanieel commented on server/persistence/src/main/kotlin/br/usp/inovacao/hubusp/server/persistence/CatalogInitiativeRepositoryImpl.kt
> +    }
Aqui vou responder sobre a separacao do construtor.

Sem problemas, esse argumento de manter a homogeneidade com relação às demais classes semelhantes é bom.

2022-12-13 12:33 UTC, jooaodanieel commented
Aqui vou comentar isso daqui:

> Só para confirmar, precisamos criar um teste para verificar se a url é null? Pelo que vimos, os testes cobertos são referentes aos parâmetros de busca apenas (e url não é um parâmetro de busca).

Certo, de fato os testes atuais cobrem os parâmetros de busca e essa alteração potencialmente não afeta os testes.

Daí eu trago um insight meio provocação: se uma alteração de código não afeta os testes atuais, o que isso nos diz sobre a nossa cobertura?

De fato, é um bad smell, um indício de que tem algo potencialmente inadequado -- potencialmente não quer dizer certeza. Vale a pena refletir sobre isso.

Na prática, o que é bom de fazer nesses casos é criar um teste pontual sobre o novo comportamento. Um unit test, ou adicionar uma nova verificação a um integration test, etc.

[se preferirem, podemos marcar de conversar sobre isso de modo síncrono]

2022-12-16 19:26 UTC, BrizaMel commented
Oi João,

então, o problema é que estamos nos enrolando para saber o que testar.
O problema era o seguinte: havia url's no banco de dado igual a null, mas a classe Initiative não permitia valores nulos para o url. Por causa disso, quando tentávamos resgatar as iniciativas do banco, ocorria um erro de tipos quando a função `toCatalogInitiative` (que transforma `InitiativeModel` em `Initiative`) era aplicada.

Então pensamos em testar a `toCatalogInitiative`. O que acha? 
No caso, construiríamos um `InitiativeModel` fake com url = null e testaríamos a capacidade dele te transformar isso num `Initiative`.

2022-12-19 12:45 UTC, jooaodanieel commented
Ois

> quando tentávamos resgatar as iniciativas do banco, ocorria um erro de tipos quando a função `toCatalogInitiative` (que transforma `InitiativeModel` em `Initiative`) era aplicada.

Esta é a situação que vocês devem tentar reproduzir.

> Então pensamos em testar a `toCatalogInitiative`. O que acha? No caso, construiríamos um `InitiativeModel` fake com url = null e testaríamos a capacidade dele te transformar isso num `Initiative`.

Perfeito! Esse é o teste ideal para essa situação. Se antes levantava uma exception inesperada ou indesejada, o teste deve fazer esse `null` e garantir que nenhuma exception surge 🚀

2023-01-11 22:01 UTC, mariliatd commented
Implementamos o teste que verifica se o InititiveModel é convertido para Initiative quando a url é nula.

2023-01-16 07:13 UTC, jooaodanieel approved these changes
Deixei duas anotações, mas já está aprovado -- fica a critério de vocês alterá-las ou não

2023-01-16 07:13 UTC, jooaodanieel commented on server/persistence/src/test/kotlin/br/usp/inovacao/hubusp/server/persistence/CatalogInitiativeRepositoryImplTest.kt
> +        assertTrue { result is Initiative }
Se não me engano, o kotlin test deixa você fazer `assertIs<Initiative>{ result }` que é um pouco mais semântico

2023-01-16 07:13 UTC, jooaodanieel commented on server/persistence/src/test/kotlin/br/usp/inovacao/hubusp/server/persistence/CatalogInitiativeRepositoryImplTest.kt
> +        )
Uma dica para facilitar a compreensão do teste é criar uma função que gera o dado inicial, assim você pode dar um nome mais claro, por exemplo, 
`val initiative = getInitiativeModelWithNullURL()`

2023-01-18 22:41 UTC, merged