Clone auspin nav
hub-usp-inovacao/platform pull request #84
Opened 2022-12-15 01:33 UTC by luizcarlosdk

This PR should be an temporary change until we find a better way to implement AUSPIN's navbar. To be easier to remove later, created a component in the root of components folder. Sorry joão

2022-12-16 10:33 UTC, jooaodanieel requested changes
Considerem mudar o nome do componente para "UniversalAuspinBar"

2022-12-16 10:33 UTC, jooaodanieel commented on frontend/components/navAuspin.vue
> +<style>
acho que aqui ta faltando um `scoped` por garantia, para evitar que esse CSS seja aplicado em outros contextos

`<style scoped> ... </style>`

2022-12-27 21:04 UTC, luizcarlosdk commented on frontend/components/navAuspin.vue
> +<style>
Ao tentar utilizar o scoped, o background-color não foi aplicado, fiquei com dúvida quanto a usar o scoped

2022-12-27 21:33 UTC, jooaodanieel commented
> Ao tentar utilizar o scoped, o background-color não foi aplicado, fiquei com dúvida quanto a usar o scoped

O scoped no estilo de um componente garante que as definições de CSS serão aplicadas apenas àquele componente e não a mais nenhum outro. Um exemplo, imagina que já exista um componente C1 na aplicação e você vai fazer um C2 que roda numa outra parte qualquer da aplicação, e você quer criar uma classe CSS chamada `.btn-primary` que potencialmente já existe. Como você não quer bagunçar o CSS do site todo, você usa o `scoped` no `style` de C2 para garantir que aquela definição `.btn-primary` feita ali será usada só ali e em mais nenhum lugar.

2022-12-27 21:33 UTC, jooaodanieel approved these changes

2022-12-27 21:52 UTC, merged