Mark required fields with asterisk
hub-usp-inovacao/platform pull request #85
Opened 2022-12-16 20:20 UTC by BrizaMel

A AUSPIN pediu para que indicássemos quais campos do formulário de atualização são obrigatórios.
Testamos um por um para ver quais são tolerados pela validação ou não e, se for impossível finalizar o formulário sem o preenchimento do campo, então colocamos um asterisco ao lado da label/descrição dele.

Signed-off-by: BrizaMel <brizamel.dias@gmail.com>
Co-authored-by: Marília Dicezare <mariliatd@gmail.com>

2022-12-19 12:52 UTC, jooaodanieel requested changes
Não verifiquei a bateria de testes, mas vale um double-check se existe um teste cuidando dos campos obrigatórios. Se existir, ignorar o resto daqui pra frente.

Vejo dois tipos de testes se encaixam: um que espera um erro quando não tem um dos campos obrigatórios; outro que espera que nenhum erro aconteça quando tem apenas os campos obrigatórios.

2022-12-19 12:52 UTC, jooaodanieel commented on backend/app/controllers/company_updates_controller.rb
> +    #ApplicationMailer.company_update_token(email, token).deliver_now
Parece código removido só para a finalidade de testes manuais. Se for este o caso, lembrem de remover o `#`

2022-12-19 12:52 UTC, jooaodanieel commented on backend/app/controllers/company_updates_controller.rb
> +    puts token
Prints de confirmação de teste manual, ao que parece. Lembrem-se de removê-los

2022-12-19 12:52 UTC, jooaodanieel commented on backend/app/controllers/company_updates_controller.rb
> +        #ApplicationMailer.confirmation_company_update(@comp_update).deliver_now
Mesma situação do `#` para testes manuais

2023-01-04 00:19 UTC, mariliatd commented
Implementamos testes nos casos em que nenhum erro acontece quando tem apenas os campos obrigatórios. O caso em que algum dos campos não era obrigatório já estava sendo testado.

2023-01-10 09:17 UTC, jooaodanieel approved these changes

2023-01-11 21:40 UTC, merged